name: Flujo para ejecutar secuencialmente las tareas de construcción y prueba
on:
  push:  
    branches: [arreglosCole]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo (solo el .jar) el código
        run: |
          chmod +x gradlew        
          ./gradlew jar
      - name: Mi uvus
        run: |
          echo "celllarod"
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Probando el código
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: Mi uvus
        run: |
          echo "celllarod"
